/* Real browser behavior over isolated public-data fixtures and a temporary PAPER ledger. */
const {chromium}=require('playwright'),{spawn}=require('node:child_process'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),port=18797;
const names={market:'Скринер',alerts:'Алерты',positions:'Позиции',settings:'Настройки'};
const legacy=/^\/api\/(?:state|scanner|scalp|live|paper|model-b|research|signals|lab-report|journal(?:-[ab])?|models-control|engine-journal|market-book)(?:\?|$)/;
async function until(check,label){const end=Date.now()+15000;while(Date.now()<end){if(await check())return;await new Promise(resolve=>setTimeout(resolve,100));}throw Error('Assistant UI: '+label);}
async function go(page,key,width){const nav=page.locator(width<=760?'.mobile-nav':'#dashboard-tabs');await nav.getByRole('button',{name:names[key],exact:true}).click();await page.locator('#page-'+key).waitFor({state:'visible'});}
(async()=>{
 const server=spawn(process.env.PYTHON||'python3',['tools/preview.py','--port',String(port),'--paper-test'],{cwd:root,stdio:['ignore','ignore','pipe']});let browser,log='';server.stderr.on('data',data=>log+=data);
 try{
  await until(()=>fetch(`http://127.0.0.1:${port}/`).then(response=>response.ok).catch(()=>false),'preview not ready');
  browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
  for(const width of [1280,390,320]){
   const page=await browser.newPage({viewport:{width,height:950}}),errors=[],requests=[],posts=[];let changed=false,manualOffline=false,manualStale=false,dropReply=false;
   page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{const url=new URL(request.url());if(url.pathname.startsWith('/api/'))requests.push(url.pathname+url.search);if(request.method()==='POST')posts.push({path:url.pathname,body:request.postDataJSON(),token:request.headers()['x-lab-control']});});
   await page.addInitScript(()=>{if(!sessionStorage.getItem('assistant-test-initialized')){sessionStorage.setItem('assistant-test-initialized','yes');sessionStorage.setItem('lab-tab','grid');localStorage.setItem('lab-start-page','research');}});
   await page.route('**/api/screener',async route=>{const response=await route.fetch(),data=await response.json();if(changed)data.rows=data.rows.map(row=>({...row,price:row.symbol==='LINKUSDT'?12345:row.price,turnover:row.symbol==='LINKUSDT'?1e10:row.turnover}));await route.fulfill({response,json:data});});
   await page.route('**/api/manual-paper',async route=>{
    if(route.request().method()==='GET'&&manualOffline)return route.fulfill({status:502,contentType:'text/html',body:'<html>Temporary gateway failure</html>'});
    if(route.request().method()==='GET'&&manualStale){const response=await route.fetch(),data=await response.json();data.updated-=20;return route.fulfill({response,json:data});}
    if(route.request().method()==='POST'&&dropReply){dropReply=false;const response=await route.fetch();assert.equal(response.status(),202);return route.abort('failed');}
    return route.continue();
   });
   await page.goto(`http://127.0.0.1:${port}/`);await page.getByLabel('Минимум оборота',{exact:true}).selectOption('0');await until(()=>page.locator('#screener-table tbody tr').count().then(count=>count===6),'six rows');
   assert.deepEqual(await page.evaluate(()=>Object.keys(LabNavigation.names)),Object.keys(names));assert.equal(await page.evaluate(()=>LabNavigation.current()),'market','removed saved routes fall back to screener');
   assert.equal(await page.locator('#dashboard-tabs button').count(),4);assert.equal(await page.locator('.mobile-nav button').count(),4);assert.equal(await page.locator('#page-grid,#page-live,#page-research,#page-tests,#page-journals,#page-chart,[data-model],#screener-orderbook,#screener-bots').count(),0);
   const scripts=await page.locator('script[src]').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('src')));assert.equal(scripts.some(src=>/\/(?:models|model-b|model-status|research|live|workspace|scanner|scalp|paper|signals|alerts|lab-report|model-journals)\.js$/.test(src)),false,'legacy modules are not loaded');
   await page.getByLabel('Сортировка монет',{exact:true}).selectOption('turnover');
   const symbols=()=>page.locator('#screener-table tbody tr').evaluateAll(rows=>rows.map(row=>row.dataset.symbol));const initial=await symbols();
   await page.locator('#screener-table tbody tr').first().evaluate(row=>row.dataset.retained='yes');changed=true;
   await until(()=>page.locator('#screener-table').textContent().then(text=>/12\s*345/.test(text)),'updated price');assert.deepEqual(await symbols(),initial,'quotes change without changing pinned order');assert.equal(await page.locator('#screener-table [data-retained="yes"]').count(),1,'quote updates retain row identity');
   await page.getByRole('button',{name:'Пересортировать',exact:true}).click();assert.equal((await symbols())[0],'LINKUSDT','explicit resort uses latest turnover');
   const star=page.locator('#screener-table').getByRole('button',{name:'Наблюдать LINKUSDT',exact:true});await star.click();assert.equal(await page.locator('#screener-table').getByRole('button',{name:'Убрать LINKUSDT из наблюдения',exact:true}).getAttribute('aria-pressed'),'true');
   assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('lab-favorites-v1'))),['LINKUSDT']);
   await page.getByLabel('Сценарий поиска',{exact:true}).selectOption('favorites');assert.deepEqual(await symbols(),['LINKUSDT']);await page.getByLabel('Сценарий поиска',{exact:true}).selectOption('all');
   await page.getByLabel('Поиск монеты',{exact:true}).fill('BTC');await until(()=>requests.some(request=>request.startsWith('/api/market-selection?')&&new URL('http://fixture'+request).searchParams.get('search')==='BTC'&&new URL('http://fixture'+request).searchParams.get('watch')==='LINKUSDT'),'watchlist remains in unrelated search scope');
   await page.getByLabel('Поиск монеты',{exact:true}).fill('LINK');await page.locator('#screener-table .coin-button').first().click();assert.equal(await page.locator('.screener-detail').getAttribute('data-symbol'),'LINKUSDT');
   await page.locator('.screener-risk>summary').click();await page.getByLabel('Вход',{exact:true}).fill('100');await page.getByLabel('Стоп',{exact:true}).fill('98');await page.getByLabel('Цель',{exact:true}).fill('104');const riskResult=page.locator('.screener-risk [role="status"]'),prepare=page.getByRole('button',{name:'Подготовить ручной PAPER-вход',exact:true});assert.equal(await riskResult.getAttribute('data-status'),'ok');assert.match(await riskResult.textContent(),/прибыль \/ риск/);assert.equal(await prepare.isDisabled(),true,'an estimate away from the current quote cannot become a PAPER draft');await page.waitForTimeout(2200);assert.equal(await page.getByLabel('Стоп',{exact:true}).inputValue(),'98','quote refresh preserves manual risk levels');await page.getByLabel('Стоп',{exact:true}).fill('100');assert.equal(await riskResult.getAttribute('data-status'),'pending','invalid stop cannot produce an estimate');assert.equal(await prepare.isDisabled(),true);
   await page.evaluate(()=>{window.assistantPrepared=null;document.addEventListener('lab-paper-draft',event=>window.assistantPrepared=event.detail,{once:true});});await page.getByLabel('Вход',{exact:true}).fill('12345');await page.getByLabel('Стоп',{exact:true}).fill('12000');await page.getByLabel('Цель',{exact:true}).fill('14000');await until(()=>prepare.isEnabled(),'fresh selected chart and valid current-price risk enable draft');await prepare.click();await page.locator('#page-positions').waitFor({state:'visible'});const prepared=await page.evaluate(()=>assistantPrepared);assert.equal(prepared.symbol,'LINKUSDT');assert.equal(prepared.side,1);assert.ok(Math.abs(prepared.low-12345*.9998)<1e-8);assert.ok(Math.abs(prepared.high-12345*1.0002)<1e-8);assert.equal(prepared.stop,12000);assert.equal(prepared.target,14000);assert.equal(prepared.interval,'1');assert.ok(Number.isFinite(prepared.stamp)&&prepared.stamp>0);assert.deepEqual(prepared.settings,{capital:600,risk_pct:.5,max_notional:100,fee_pct:.055,slippage_pct:.05,min_rr:1.5});assert.equal(posts.length,0,'preparing a draft never sends an execution command');await page.locator('#manual-paper .manual-review').waitFor({state:'visible'});assert.match(await page.locator('#manual-paper .manual-review').textContent(),/LINKUSDT/);await page.getByRole('button',{name:'Убрать план',exact:true}).click();assert.equal(await page.locator('#manual-paper .manual-review').isHidden(),true);assert.equal(posts.length,0,'cancelling review never executes the draft');
   await go(page,'settings',width);await page.getByLabel('Плотность интерфейса',{exact:true}).selectOption('compact');await page.reload();await page.locator('#page-settings').waitFor({state:'visible'});assert.equal(await page.locator('body').getAttribute('data-density'),'compact');assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('lab-favorites-v1'))),['LINKUSDT']);
   await go(page,'positions',width);const manual=page.locator('#manual-paper');await until(()=>manual.getByRole('button',{name:'Пауза ручных входов',exact:true}).isEnabled(),'manual token and fresh snapshot');
   dropReply=width===1280;await manual.getByRole('button',{name:'Пауза ручных входов',exact:true}).click();
   if(width===1280){const retry=manual.getByRole('button',{name:'Повторить тот же PAPER-запрос',exact:true});await until(()=>retry.isVisible(),'uncertain reply retains idempotent request');await retry.click();await until(()=>retry.isHidden(),'retry confirmed');const attempts=posts.filter(post=>post.path==='/api/manual-paper'&&post.body.action==='pause');assert.equal(attempts.length,2);assert.deepEqual(attempts[0].body,attempts[1].body,'the retry cannot create a second command');}
   await until(()=>manual.getByRole('button',{name:'Разрешить ручные входы',exact:true}).isEnabled(),'pause applied');assert.equal(posts.every(post=>post.path==='/api/manual-paper'&&typeof post.body.id==='string'&&post.token==='isolated-preview-token'),true,'only authenticated manual PAPER commands are sent');
   manualStale=true;await until(()=>manual.getByRole('button',{name:'Разрешить ручные входы',exact:true}).isDisabled(),'stale manual snapshot disables commands');manualStale=false;
   await until(()=>manual.getByRole('button',{name:'Разрешить ручные входы',exact:true}).isEnabled(),'fresh snapshot recovers commands');manualOffline=true;await until(()=>manual.textContent().then(text=>text.includes('неполные данные')),'gateway HTML is handled');assert.doesNotMatch(await manual.textContent(),/Unexpected token/);assert.equal(await manual.getByRole('button',{name:'Разрешить ручные входы',exact:true}).isDisabled(),true);manualOffline=false;
   await until(()=>manual.getByRole('button',{name:'Разрешить ручные входы',exact:true}).isEnabled(),'connection recovery');await manual.getByRole('button',{name:'Разрешить ручные входы',exact:true}).click();await until(()=>manual.getByRole('button',{name:'Пауза ручных входов',exact:true}).isEnabled(),'resume applied');
   await page.evaluate(()=>document.dispatchEvent(new CustomEvent('lab-paper-draft',{detail:{symbol:'BTCUSDT',side:1,low:99.4,high:99.6,stop:98,target:104,stamp:Date.now()/1000,interval:'5',settings:{capital:600,risk_pct:.5,max_notional:100,fee_pct:.055,slippage_pct:.05,min_rr:1.5},reason:'Изолированная проверка ручного PAPER'}})));
   const open=manual.getByRole('button',{name:'Открыть виртуальную позицию',exact:true}),reason=page.getByLabel('Причина ручного входа',{exact:true});await until(()=>open.isEnabled(),'draft review ready');await reason.fill('Ручной сценарий со стопом и ограничением риска');await page.waitForTimeout(2200);assert.equal(await reason.inputValue(),'Ручной сценарий со стопом и ограничением риска','snapshot refresh preserves the typed reason');await open.click();
   await until(()=>manual.locator('.position-symbol').textContent().then(text=>text.includes('BTCUSDT')),'server accepts and stores PAPER entry');assert.equal(await manual.locator('.manual-review').isHidden(),true);await page.reload();await until(()=>manual.getByRole('button',{name:'Закрыть ручную PAPER-позицию',exact:true}).isEnabled(),'durable position survives reload');assert.match(await manual.locator('.position-reason').textContent(),/ограничением риска/);
   manualStale=true;await until(()=>manual.getByRole('button',{name:'Закрыть ручную PAPER-позицию',exact:true}).isDisabled(),'stale marks disable closing');assert.equal(await manual.locator('dd').nth(1).textContent(),'—','stale snapshot never exposes current net');manualStale=false;await until(()=>manual.getByRole('button',{name:'Закрыть ручную PAPER-позицию',exact:true}).isEnabled(),'fresh closing quote');await manual.getByRole('button',{name:'Закрыть ручную PAPER-позицию',exact:true}).click();await until(()=>manual.locator('.position-symbol').count().then(count=>count===0),'manual PAPER closes on server');
   for(const key of Object.keys(names)){await go(page,key,width);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+width+' '+key);const nav=page.locator(width<=760?'.mobile-nav':'#dashboard-tabs');assert.equal(await nav.locator('[aria-pressed="true"]').count(),1);}
   assert.deepEqual(requests.filter(request=>legacy.test(request)),[],'no deleted section requests');assert.equal(posts.every(post=>post.path==='/api/manual-paper'&&post.token==='isolated-preview-token'),true);assert.deepEqual(errors,[]);await page.close();
  }
  console.log('Assistant UI passed: 1280/390/320, lean navigation/network, fixed ordering, watch/search/reload, risk-to-PAPER review without execution, PAPER auth/retry/open/close/durable storage/stale/offline recovery.');
 }catch(error){console.error(log);throw error;}finally{if(browser)await browser.close();server.kill('SIGTERM');}
})().catch(error=>{console.error(error);process.exitCode=1;});
