const {test}=require('node:test'),assert=require('node:assert/strict');
const {modelPosition,manualPosition}=require('../src/trading-panel/positions.js');
const s={updated:100,phase:'running',market_time:100,balance:599.945,equity:600.4,config:{stop_loss:.4,take_profit:.6},position:{symbol:'BTCUSDT',side:1,entry:100,quantity:1,opened:90,entry_fee:.055,funding:.01}};
test('position net uses model equity, opening fee and recorded funding',()=>{const v=modelPosition('A',s,101).position;assert.ok(Math.abs(v.net-.41)<1e-9);assert.equal(v.stop,.4);assert.equal(v.target,.6);assert.match(v.reason,/не записана/);});
test('halted B remains saved; net is not presented as current',()=>{const v=modelPosition('B',{...s,phase:'halted',position:{...s.position,stop_usdt:.7,target_usdt:1.05}},101).position;assert.equal(v.current,false);assert.equal(v.net,null);assert.equal(v.stop,.7);});
test('stale marks, stopped service and missing quote time hide net',()=>{for(const source of [{...s,market_time:80},{...s,updated:80},{...s,market_time:undefined}])assert.equal(modelPosition('A',source,101).position.net,null);assert.equal(modelPosition('A',s,101,{fresh:true,unit_active:'inactive',phase:'halted'}).position.current,false);});
test('C/D exit rules keep net USDT units and per-position quote freshness',()=>{const source={...s,config:{stop:.4,target:.6},position:{...s.position,quote_time:100,funding:0}};assert.equal(modelPosition('C',source,101).position.target,.6);assert.equal(modelPosition('D',{...source,position:{...source.position,quote_time:80}},101).position.net,null);});
test('malformed position is distinct from no open position',()=>{assert.equal(modelPosition('A',{...s,position:{...s.position,quantity:0}},101).invalid,true);assert.equal(modelPosition('A',{...s,position:null},101).invalid,false);});
test('manual quote expiry and funding uncertainty hide current net',()=>{const source={status:'ok',updated:100,position:{mark:{quote_time:100,complete:true,net:.2}}};assert.equal(manualPosition(source,101).net,.2);assert.equal(manualPosition(source,110).net,null);assert.equal(manualPosition({...source,position:{mark:{quote_time:100,complete:false,net:null}}},101).current,false);});
